version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: game-catalog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamecatalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - game-catalog-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  catalog-service:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: game-catalog-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=gamecatalog
      - DATABASE_SSLMODE=disable
      - SERVER_PORT=8080
      - LOGGER_LEVEL=info
    ports:
      - "8080:8080"
    networks:
      - game-catalog-network

networks:
  game-catalog-network:
    driver: bridge

volumes:
  postgres_data: