server:
  port: 8080
  readTimeout: 5s
  writeTimeout: 10s
  idleTimeout: 120s

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: gamecatalog
  sslmode: disable

logger:
  level: info
